package MastermindB;
import java.util.*;                                    


public class Main {
	
	static String PlayGame="P";                                   // These are the variables that can be used throughout the main class   //                              
	static String Choice1 = "Y";                                 //  The variables include "PlayGame" for starting the game, "Choice 1&2"//
	static String Choice2 = "N";                                 //   for the choosing the option whether the player wants to play with or //
	static String Quit = "Q";                                   //   without repeating colours, the "Quit" is if the player wants to quit the//
	static int PlayerScore = 0;                                 //    game, "PlayerScore" is the score when the player wins the game,//
	                                                            //   "ComputerScore" is the score when the player loses and the computer wins//
	static boolean Continue;                                   // Boolean "Continue" used in while loops so that the player can play again //
	static int Count1=0;                                       // "Count1" for counting the total games played //
	

	public static void main(String[] args) {                          // main method which is used for the game //

		
		@SuppressWarnings("resource")                 
		Scanner scan = new Scanner (System.in);
		System.out.println("Welcome to Mastermind");                         // Welcome message // 
		System.out.println("---------------------");
		System.out.println("Press P to Play");                               // Play option //
		System.out.println("Press Q to Quit");                              // Quit option // 
		 
	    String NewGame = scan.nextLine();
	    
	    
	    
		
		if (NewGame.equalsIgnoreCase(PlayGame))
		{System.out.println("List of Colors You can Choose: \"R - Red\", \"B - Blue\", \"O - Orange\", \"G - Green\", \"Y - Yellow\", \"P - Pink\"");
		
		System.out.println("");
		
		System.out.println("To win this game you have to guess four colors generated by the computer. You will have 12 guesses.\nEach time "                      
				            + " you guess a right colour in the right position, plus sign will be added to ColourRightPos and minus if the colour is in the wrong position"  // Instructions//
				            + "\nTo win this game, you have to get 4 plus signs and you will lose if you run out of guesses.");
		
		System.out.println("");
		
		System.out.println("Do you want to play with repeating colours? Y/N");                        //   Option to choose whether to play with or without repeating colours //
	
		
		
		String ChooseOption = scan.nextLine();
		
		if (ChooseOption.equalsIgnoreCase(Choice1))                 // This if-statement if the player wants to play with repeating colours // 
		{ 
			do {
				
			RepeatingColours obj = new RepeatingColours();                   
		     obj.RC(); 
		     
		    
		     RepeatingColours.ColourRightPos="";
			  RepeatingColours.ColourWrongPos="";
			  RepeatingColours.Guess=12;
			  
			  System.out.println("");
			  
		 	System.out.println("Press P to Play again");                           // Options to play again or quit //
			
		 	System.out.println("Press Q to Quit");
			
			  
			    
			String Game1 = scan.nextLine();
			
			Count1++;
			
			if (Game1.equalsIgnoreCase(PlayGame))                            // if-statement if the player wants to play again // 
			{Continue = true;
			
			}
			
			else if (Game1.equalsIgnoreCase(Quit))                           // else-if statement if the player decides to quit // 
			{
				Continue = false;
				
			}
		    }
		    while (Continue== true);                                       // while loop ends if the player quits  //
		}
		
		
		
		
		
		
		else if (ChooseOption.equalsIgnoreCase(Choice2)) {                       // This else-if statement is if the player wants to play without repeating colours//
			
			do {
			
			NoRepeatingColour obj2 = new NoRepeatingColour();
			
			obj2.NRC();
			
			 NoRepeatingColour.ColourRightPos="";
			 
			 NoRepeatingColour.Guess=12;
			 
			 System.out.println("");
			 
			System.out.println("Press P to Play again");                                 // Options to play again or quit // 
			
			System.out.println("Press Q to Quit");
			
			
			String Game2 = scan.nextLine();
			
			Count1++;
			
			if (Game2.equalsIgnoreCase(PlayGame))
			{Continue = true;
			
			}
			
			else if (Game2.equalsIgnoreCase(Quit))                                     // else-if statement if the player decides to quit // 
			{
				Continue = false;
				
			}
		    }
		    while (Continue== true);                                                        // while loop ends if the player quits  //
			
		}
		}
		
		
		else if (NewGame.equalsIgnoreCase(Quit))
			{System.out.println("Thanks for choosing Mastermind");                      // Quit message // 
		}
		
		
		
		
		
		 if (Continue == false) {                                          // this if-statement outputs the EndGameResults() method which shows the end game results // 
			 
			 EndGameResults();
		 }
		
		
		
	}
	
	/* This method is used by the methods of the other two classes
	 *  when the player wins the game by correctly guessing the 
	 *  colours generated by the computer then it will show a
	 *  congratulatory message that it has won the game and it
	 *  will output the playerscore as the player has won the game  */
	
	
	
	public static void win() {              
		
		
	    {System.out.println("Congratutalations!! You have won the game");
	  
	    PlayerScore+=1;
	    System.out.println( "PlayerScore:" + PlayerScore);
	    }
	    
		}
	
	  
	

	
	/* This method will show the end game results when the player
	 * decides to quit the game. It will the total games played by
	 * the player, the playerscore shows the amount of times the player
	 * has won the game and the computerscore shows the amount of time 
	 * the player has lost the game.   */
	
	
	public static void EndGameResults() {
		
		
		
		int total = RepeatingColours.ComputerScore + NoRepeatingColour.ComputerScore;
		
		System.out.println("End Game Results");                                 
		System.out.println("-----------------");
		System.out.println("Total Games Played: "+ Count1);
		System.out.println("Total PlayerScore: "+ PlayerScore );
		System.out.println("Total ComputerScore: "+ total);
	}
	
	
	
	
	}


